<?php

declare (strict_types=1);
namespace Drupal\Core\Asset;

use Drupal\Component\Datetime\Time_Interface;
use Drupal\Component\Utility\Url_Helper;
use Drupal\Core\Config\Config_Factory_Interface;
use Drupal\Core\File\File_System_Interface;
use Drupal\Core\File\File_Url_Generator_Interface;
use Drupal\Core\Language\Language_Manager_Interface;
use Drupal\Core\Site\Settings;
use Drupal\Core\Theme\Theme_Manager_Interface;
use Symfony\Component\Http_Foundation\Request_Stack;
/**
 * Optimizes CSS assets.
 */
class Css_Collection_Optimizer_Lazy implements Asset_Collection_Group_Optimizer_Interface
{
    use Asset_Group_Set_Hash_Trait;
    /**
     * Constructs a CssCollectionOptimizerLazy.
     *
     * @param \Drupal\Core\Asset\AssetCollectionGrouperInterface $grouper
     *   The grouper for CSS assets.
     * @param \Drupal\Core\Asset\AssetOptimizerInterface $optimizer
     *   The asset optimizer.
     * @param \Drupal\Core\Theme\ThemeManagerInterface $themeManager
     *   The theme manager.
     * @param \Drupal\Core\Asset\LibraryDependencyResolverInterface $dependencyResolver
     *   The library dependency resolver.
     * @param \Symfony\Component\HttpFoundation\RequestStack $requestStack
     *   The request stack.
     * @param \Drupal\Core\File\FileSystemInterface $fileSystem
     *   The file system service.
     * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
     *   The config factory.
     * @param \Drupal\Core\File\FileUrlGeneratorInterface $fileUrlGenerator
     *   The file URL generator.
     * @param \Drupal\Component\Datetime\TimeInterface $time
     *   The time service.
     * @param \Drupal\Core\Language\LanguageManagerInterface $languageManager
     *   The language manager.
     */
    public function __construct(protected readonly Asset_Collection_Grouper_Interface $grouper, protected readonly Asset_Optimizer_Interface $optimizer, protected readonly Theme_Manager_Interface $theme_manager, protected readonly Library_Dependency_Resolver_Interface $dependency_resolver, protected readonly Request_Stack $request_stack, protected readonly File_System_Interface $file_system, protected readonly Config_Factory_Interface $config_factory, protected readonly File_Url_Generator_Interface $file_url_generator, protected readonly Time_Interface $time, protected readonly Language_Manager_Interface $language_manager)
    {
    }
    /**
     * {@inheritdoc}
     * @return mixed[]
     */
    public function optimize(array $css_assets, array $libraries): array
    {
        // File names are generated based on library/asset definitions. This
        // includes a hash of the assets and the group index. Additionally, the full
        // set of libraries, already loaded libraries and theme are sent as query
        // parameters to allow a PHP controller to generate a valid file with
        // sufficient information. Files are not generated by this method since
        // they're assumed to be successfully returned from the URL created whether
        // on disk or not.
        // Group the assets.
        $css_groups = $this->grouper->group($css_assets);
        $css_assets = [];
        foreach ($css_groups as $order => $css_group) {
            // We have to return a single asset, not a group of assets. It is now up
            // to one of the pieces of code in the switch statement below to set the
            // 'data' property to the appropriate value.
            $css_assets[$order] = $css_group;
            if ($css_group['type'] === 'file') {
                // No preprocessing, single CSS asset: just use the existing URI.
                if (!$css_group['preprocess']) {
                    $uri = $css_group['items'][0]['data'];
                    $css_assets[$order]['data'] = $uri;
                } else {
                    // To reproduce the full context of assets outside of the request,
                    // we must know the entire set of libraries used to generate all CSS
                    // groups, whether or not files in a group are from a particular
                    // library or not.
                    $css_assets[$order]['preprocessed'] = true;
                }
            }
            if ($css_group['type'] === 'external') {
                // We don't do any aggregation and hence also no caching for external
                // CSS assets.
                $uri = $css_group['items'][0]['data'];
                $css_assets[$order]['data'] = $uri;
            }
        }
        // All asset group URLs will have exactly the same query arguments, except
        // for the delta, so prepare them in advance.
        $query_args = ['language' => $this->language_manager->get_current_language()->get_id(), 'theme' => $this->theme_manager->get_active_theme()->get_name(), 'include' => Url_Helper::compress_query_parameter(implode(',', $this->dependency_resolver->get_minimal_representative_subset($libraries)))];
        $ajax_page_state = $this->request_stack->get_current_request()->attributes->get('ajax_page_state');
        $already_loaded = isset($ajax_page_state) ? explode(',', (string) $ajax_page_state['libraries']) : [];
        if ($already_loaded) {
            $query_args['exclude'] = Url_Helper::compress_query_parameter(implode(',', $this->dependency_resolver->get_minimal_representative_subset($already_loaded)));
        }
        // Generate a URL for each group of assets, but do not process them inline,
        // this is done using optimizeGroup() when the asset path is requested.
        foreach ($css_assets as $order => $css_asset) {
            if (!empty($css_asset['preprocessed'])) {
                $query = ['delta' => "{$order}"] + $query_args;
                $filename = 'css_' . $this->generate_hash($css_asset) . '.css';
                $uri = 'assets://css/' . $filename;
                $css_assets[$order]['data'] = $this->file_url_generator->generate_string($uri) . '?' . Url_Helper::build_query($query);
            }
            unset($css_assets[$order]['items']);
        }
        return $css_assets;
    }
    /**
     * {@inheritdoc}
     */
    public function delete_all(): void
    {
        if (!\is_dir('assets://css')) {
            return;
        }
        $directory_iterator = new \Directory_Iterator('assets://css');
        $threshold = Settings::get('aggregate_gc_threshold', 86400 * 45);
        foreach ($directory_iterator as $file) {
            if ($file->is_file() && $this->time->get_request_time() - $file->get_mtime() > $threshold) {
                $this->file_system->delete($file->get_path_name());
            }
        }
    }
    /**
     * {@inheritdoc}
     */
    public function optimize_group(array $group): string
    {
        // Optimize each asset within the group.
        $data = '';
        $current_license = false;
        foreach ($group['items'] as $css_asset) {
            // Ensure license information is available as a comment after
            // optimization.
            if ($css_asset['license'] !== $current_license) {
                $data .= '/* @license ' . $css_asset['license']['name'] . ' ' . $css_asset['license']['url'] . " */\n";
            }
            $current_license = $css_asset['license'];
            // Only external minified files can skip optimization.
            // Local files (even if minified) must be processed to ensure resource
            // paths are rewritten relative to the cached aggregated file location.
            $is_minified = isset($css_asset['minified']) && $css_asset['minified'];
            $is_external = isset($css_asset['type']) && $css_asset['type'] === 'external';
            if ($is_minified && $is_external) {
                $data .= file_get_contents($css_asset['data']);
            } else {
                $data .= $this->optimizer->optimize($css_asset);
            }
        }
        // Per the W3C specification at
        // https://www.w3.org/TR/REC-CSS2/cascade.html#at-import, @import rules must
        // precede any other style, so we move those to the top. The regular
        // expression is expressed in NOWDOC since it is detecting backslashes as
        // well as single and double quotes. It is difficult to read when
        // represented as a quoted string.
        $regexp = <<<'REGEXP'
        /@import\s*(?:'(?:\\'|.)*'|"(?:\\"|.)*"|url\(\s*(?:\\[\)\'\"]|[^'")])*\s*\)|url\(\s*'(?:\'|.)*'\s*\)|url\(\s*"(?:\"|.)*"\s*\)).*;/iU
        REGEXP;
        preg_match_all($regexp, $data, $matches);
        $data = preg_replace($regexp, '', $data);
        return implode('', $matches[0]) . (!empty($matches[0]) ? "\n" : '') . $data;
    }
}