<?php

declare (strict_types=1);
namespace Drupal\Core\Asset;

use Drupal\Component\Datetime\Time_Interface;
use Drupal\Component\Utility\Url_Helper;
use Drupal\Core\Config\Config_Factory_Interface;
use Drupal\Core\File\File_System_Interface;
use Drupal\Core\File\File_Url_Generator_Interface;
use Drupal\Core\Language\Language_Manager_Interface;
use Drupal\Core\Site\Settings;
use Drupal\Core\Theme\Theme_Manager_Interface;
use Symfony\Component\Http_Foundation\Request_Stack;
/**
 * Optimizes JavaScript assets.
 */
class Js_Collection_Optimizer_Lazy implements Asset_Collection_Group_Optimizer_Interface
{
    use Asset_Group_Set_Hash_Trait;
    /**
     * Constructs a JsCollectionOptimizerLazy.
     *
     * @param \Drupal\Core\Asset\AssetCollectionGrouperInterface $grouper
     *   The grouper for JS assets.
     * @param \Drupal\Core\Asset\AssetOptimizerInterface $optimizer
     *   The asset optimizer.
     * @param \Drupal\Core\Theme\ThemeManagerInterface $themeManager
     *   The theme manager.
     * @param \Drupal\Core\Asset\LibraryDependencyResolverInterface $dependencyResolver
     *   The library dependency resolver.
     * @param \Symfony\Component\HttpFoundation\RequestStack $requestStack
     *   The request stack.
     * @param \Drupal\Core\File\FileSystemInterface $fileSystem
     *   The file system service.
     * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
     *   The config factory.
     * @param \Drupal\Core\File\FileUrlGeneratorInterface $fileUrlGenerator
     *   The file URL generator.
     * @param \Drupal\Component\Datetime\TimeInterface $time
     *   The time service.
     * @param \Drupal\Core\Language\LanguageManagerInterface $languageManager
     *   The language manager.
     */
    public function __construct(protected readonly Asset_Collection_Grouper_Interface $grouper, protected readonly Asset_Optimizer_Interface $optimizer, protected readonly Theme_Manager_Interface $theme_manager, protected readonly Library_Dependency_Resolver_Interface $dependency_resolver, protected readonly Request_Stack $request_stack, protected readonly File_System_Interface $file_system, protected readonly Config_Factory_Interface $config_factory, protected readonly File_Url_Generator_Interface $file_url_generator, protected readonly Time_Interface $time, protected readonly Language_Manager_Interface $language_manager)
    {
    }
    /**
     * {@inheritdoc}
     * @return mixed[]
     */
    public function optimize(array $js_assets, array $libraries): array
    {
        // File names are generated based on library/asset definitions. This
        // includes a hash of the assets and the group index. Additionally, the full
        // set of libraries, already loaded libraries and theme are sent as query
        // parameters to allow a PHP controller to generate a valid file with
        // sufficient information. Files are not generated by this method since
        // they're assumed to be successfully returned from the URL created whether
        // on disk or not.
        // Group the assets.
        $js_groups = $this->grouper->group($js_assets);
        $js_assets = [];
        foreach ($js_groups as $order => $js_group) {
            // We have to return a single asset, not a group of assets. It is now up
            // to one of the pieces of code in the switch statement below to set the
            // 'data' property to the appropriate value.
            $js_assets[$order] = $js_group;
            switch ($js_group['type']) {
                case 'file':
                    // No preprocessing, single JS asset: just use the existing URI.
                    if (!$js_group['preprocess']) {
                        $uri = $js_group['items'][0]['data'];
                        $js_assets[$order]['data'] = $uri;
                    } else {
                        // To reproduce the full context of assets outside of the request,
                        // we must know the entire set of libraries used to generate all CSS
                        // groups, whether or not files in a group are from a particular
                        // library or not.
                        $js_assets[$order]['preprocessed'] = true;
                    }
                    break;
                case 'external':
                    // We don't do any aggregation and hence also no caching for external
                    // JS assets.
                    $uri = $js_group['items'][0]['data'];
                    $js_assets[$order]['data'] = $uri;
                    break;
                case 'setting':
                    $js_assets[$order]['data'] = $js_group['data'];
                    break;
            }
        }
        if ($libraries) {
            // All group URLs have the same query arguments apart from the delta and
            // scope, so prepare them in advance.
            $language = $this->language_manager->get_current_language()->get_id();
            $query_args = ['language' => $language, 'theme' => $this->theme_manager->get_active_theme()->get_name(), 'include' => Url_Helper::compress_query_parameter(implode(',', $this->dependency_resolver->get_minimal_representative_subset($libraries)))];
            $ajax_page_state = $this->request_stack->get_current_request()->attributes->get('ajax_page_state');
            $already_loaded = isset($ajax_page_state) ? explode(',', (string) $ajax_page_state['libraries']) : [];
            if ($already_loaded) {
                $query_args['exclude'] = Url_Helper::compress_query_parameter(implode(',', $this->dependency_resolver->get_minimal_representative_subset($already_loaded)));
            }
            // Generate a URL for the group, but do not process it inline, this is
            // done by \Drupal\system\controller\JsAssetController.
            foreach ($js_assets as $order => $js_asset) {
                if (!empty($js_asset['preprocessed'])) {
                    $query = ['scope' => $js_asset['scope'] === 'header' ? 'header' : 'footer', 'delta' => "{$order}"] + $query_args;
                    // Add a filename prefix to mitigate ad blockers which can block
                    // any script beginning with 'ad'.
                    $filename = 'js_' . $this->generate_hash($js_asset) . '.js';
                    $uri = 'assets://js/' . $filename;
                    $js_assets[$order]['data'] = $this->file_url_generator->generate_string($uri) . '?' . Url_Helper::build_query($query);
                }
                unset($js_assets[$order]['items']);
            }
        }
        return $js_assets;
    }
    /**
     * {@inheritdoc}
     */
    public function delete_all(): void
    {
        if (!\is_dir('assets://js')) {
            return;
        }
        $directory_iterator = new \Directory_Iterator('assets://js');
        $threshold = Settings::get('aggregate_gc_threshold', 86400 * 45);
        foreach ($directory_iterator as $file) {
            if ($file->is_file() && $this->time->get_request_time() - $file->get_mtime() > $threshold) {
                $this->file_system->delete($file->get_path_name());
            }
        }
    }
    /**
     * {@inheritdoc}
     */
    public function optimize_group(array $group): string
    {
        $data = '';
        $current_license = false;
        foreach ($group['items'] as $js_asset) {
            // Ensure license information is available as a comment after
            // optimization.
            if ($js_asset['license'] !== $current_license) {
                $data .= '/* @license ' . $js_asset['license']['name'] . ' ' . $js_asset['license']['url'] . " */\n";
            }
            $current_license = $js_asset['license'];
            // Optimize this JS file, but only if it's not yet minified.
            if (isset($js_asset['minified']) && $js_asset['minified']) {
                $data .= file_get_contents($js_asset['data']);
            } else {
                $data .= $this->optimizer->optimize($js_asset);
            }
            // Append a ';' and a newline after each JS file to prevent them from
            // running together.
            $data .= ";\n";
        }
        // Remove unwanted JS code that causes issues.
        return $this->optimizer->clean($data);
    }
}