config.sync:
  path: '/admin/config/development/configuration'
  defaults:
    _form: '\Drupal\config\Form\Config_Sync'
    _title: 'Synchronize'
  requirements:
    _permission: 'synchronize configuration'

config.diff:
  path: '/admin/config/development/configuration/sync/diff/{source_name}/{target_name}'
  defaults:
    _controller: '\Drupal\config\Controller\Config_Controller::diff'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'

config.diff_collection:
  path: '/admin/config/development/configuration/sync/diff_collection/{collection}/{source_name}/{target_name}'
  defaults:
    _controller: '\Drupal\config\Controller\Config_Controller::diff'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'

config.export_download:
  path: '/admin/config/development/configuration/full/export-download'
  defaults:
    _controller: '\Drupal\config\Controller\Config_Controller::downloadExport'
  requirements:
    _permission: 'export configuration'

config.export_full:
  path: '/admin/config/development/configuration/full/export'
  defaults:
    _form: '\Drupal\config\Form\Config_Export_Form'
    _title: 'Export'
  requirements:
    _permission: 'export configuration'

config.import_full:
  path: '/admin/config/development/configuration/full/import'
  defaults:
    _form: '\Drupal\config\Form\Config_Import_Form'
    _title: 'Import'
  requirements:
    _permission: 'import configuration'

config.import_single:
  path: '/admin/config/development/configuration/single/import'
  defaults:
    _title: 'Single import'
    _form: '\Drupal\config\Form\Config_Single_Import_Form'
  requirements:
    _permission: 'import configuration'

config.export_single:
  path: '/admin/config/development/configuration/single/export/{config_type}/{config_name}'
  defaults:
    _title: 'Single export'
    _form: '\Drupal\config\Form\Config_Single_Export_Form'
    config_type: ''
    config_name: ''
  requirements:
    _permission: 'export configuration'
