<?php

declare (strict_types=1);
namespace Drupal\Core\Ajax;

use Drupal\Core\Asset\Attached_Assets;
/**
 * AJAX command for conveying changed tabledrag rows.
 *
 * This command is provided an id of a table row then does the following:
 * - Marks the row as changed.
 * - If a message generated by the tableDragChangedWarning is not present above
 *   the table the row belongs to, that message is added there.
 *
 * @see Drupal.AjaxCommands.prototype.tabledragChanged
 *
 * @ingroup ajax
 */
class Tabledrag_Warning_Command implements Command_Interface, Command_With_Attached_Assets_Interface
{
    /**
     * Constructs a TableDragWarningCommand object.
     *
     * @param string $id
     *   The id of the changed row.
     * @param string $tabledrag_instance
     *   The identifier of the tabledrag instance.
     */
    public function __construct(protected string $id, protected string $tabledrag_instance)
    {
    }
    /**
     * {@inheritdoc}
     */
    public function render(): array
    {
        return ['command' => 'tabledragChanged', 'id' => $this->id, 'tabledrag_instance' => $this->tabledrag_instance];
    }
    /**
     * {@inheritdoc}
     */
    public function get_attached_assets(): \Drupal\Core\Asset\Attached_Assets
    {
        $assets = new Attached_Assets();
        $assets->set_libraries(['core/drupal.tabledrag.ajax']);
        return $assets;
    }
}